#!/usr/bin/env sh

top_working_dir=$1
remote_repo=$2
local_repo_1=$3
local_repo_2=$4

cd $local_repo_1
greatest_version=$(pkgit-greatest-version)
if [ "$5" = "$greatest_version" ]; then
    exit 0
else
    echo "Failed test for greatest version. Expected version $5, actual version $greatest_version"
    exit 1
fi
