#!/usr/bin/env sh

#
# Try to find the .git directory starting from the current directory and working upwards
# Continue working upwards until either the .git directory is found or the "/" directory is found
# Echo out the directory when it is found.  
# Exit code non-zero on error
#
set -e

#
# Ensure that the $1 of this function is not the root directory of the file system
# If it is then exit the script with an error code
#
ensure_not_root_directory()
{
    current_dir=$(pwd)
    cd $1 >/dev/null 2>&1 
    if [ $? != 0 ] || [ $(pwd) = / ]; then
        cd $current_dir >/dev/null 2>&1 
        exit 1   # Note the early exit from this script if we have hit the root directory of the file system
    fi
    cd $current_dir >/dev/null 2>&1 
}

#
# Turn a directory like /home/geoff/../matthew into /home/matthew
#
fold_dots_in_path()
{
    current_dir=$(pwd)
    cd $1 2>&1 /dev/null
    pwd
    cd $current_dir >/dev/null 2>&1 
}

test_dir=$(pwd)
ensure_not_root_directory $test_dir

while [ ! -e $test_dir/.git ]
do
    test_dir=$test_dir/..
    ensure_not_root_directory $test_dir
done

fold_dots_in_path $test_dir

