#!/usr/bin/env sh

usage()
{
    echo "Usage: $(basename $0) [-?|-h|--help] [--version] [branch-version-number]"
    echo "Find the greatest version number tagged in the local repository on the curernt branch."
    echo "It is a precondition that the repository has tags of the form packagename.version-release"
    echo "For example, if the repository contains tags pj_one.1.0.0-1 and vv.1.0.2-1, "
    echo "then the greatest version number is 1.0.2 with a release numer of 1."
    echo "If a branch-version-number is specified then tags are restricted to be of the form packagename.$1-release"
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]; then
    usage
    exit
fi

if [ "$1" = "--version" ]; then
    echo PKGIT_PROJECT_VERSION
    exit
fi

if [ -z "$1" ]; then
    tag_specification='*-*.*.*-*'
else
    tag_specification='*'-"$1"-'*'
fi

# Find the latest tag on the current branch and strip off the leading package name
git describe --abbrev=0 --match "$tag_specification" | rev | cut -d- -f-2 | rev

