#!/usr/bin/env sh

# Publish a package using the spec file in the current directory
umask 0002

usage()
{
cat <<EOF
Usage: $(basename $0) [-h|--help] [--debug] [--version] [--sandbox] [--unclean] [-v|--verbose] [-q|quiet] [-p|--pretend] [-m|--message=<meaningful message>]

Publish a package using the spec file in the current directory

Options:
  -h|--help  Print this message
  --debug  Executes "set -x" to put the shell into debug mode
  --version  Print the version number and exit
  --sandbox  Don't tag the central repo, don't worry if we are ahead of the central repo.  Use 0.0.0-0 as the version-release number
  --unclean  Package up without checking that files are checked in.  This implies --sandbox. Note that --sandbox still wants you to check your work in to the local repo and this lets you work around that restriction.
  -s|--spec     Specify a spec file to build.  If no spec file is specified pkgit defaults to using the alphabetically first spec file.
  -v|--verbose  Print out extra information rather than showing nothing  
  -q|--quiet    Turn verbose information off
  -p|--pretend  Do all the work but don't actually execute the git tag command. Works best in conjunction with --verbose
  -m|--message  The message to be put into the annotated tag.  Defaults to "Tagging in preparation for packaging"
  
Examples:
$(basename $0) -m "The Heisenbug is gone."
        
EOF
   
exit 0
}

die()
{
    echo >&2 "$@"
    exit 1
}

verbose_echo()
{
    if [ -n "$verbose" ]; then
        echo "$@"
    fi
}

# Parse command line arguments. We accept the usual GNU short and long args and convert them to space separated arguments
# Note that we use `"$@"' to let each command-line parameter expand to a separate word. The quotes around `$@' are essential!
# We need TEMP as the `eval set --' would nuke the return value of getopt.
TEMP=$(getopt -s sh -o hvqps:m: -l "help,debug,version,verbose,quiet,pretend,spec:,message:,sandbox,unclean" -n "$(basename $0)" -- "$@")
if [ $? != 0 ] ; then echo "Could not parse command line options..." >&2 ; usage ; fi
eval set -- "$TEMP"  # Note the quotes around '$TEMP': they are essential!

message="Tagging in preparation for packaging"
verbose="--verbose"   # Be verbose by default.  The users seem to prefer that rather than complete silence

# By default, use the first spec file found.  Command line overrideable.
spec=$(ls -1 *.spec |head -1 2> /dev/null)

# Overide the defaults with anything from the command line
while true; do
    case "$1" in
        "--debug"         )  set -x;debug="--debug" ;;
        "-h"|"--help"     )  usage ;;
        "--version"       )  echo PKGIT_PROJECT_VERSION; exit 0 ;;
        "-v"|"--verbose"  )  verbose="--verbose" ;;
        "-q"|"--quiet"    )  unset verbose ;;
        "-p"|"--pretend"  )  pretend="--pretend" ;;
        "-m"|"--message"  )  shift; message="$1" ;;
        "-s"|"--spec"     )  shift; spec="$1" ;;
        "--sandbox"       )  sandbox="--sandbox" ;;
        "--unclean"       )  unclean="--unclean"; sandbox="--sandbox" ;;
        "--"              )  shift ; break ;;
        *                 )  die "getopt error!" ; exit 1 ;;
    esac
    shift
done


# Check that we have a spec file to rpmbuild
if [ "$spec" = "" ]; then
    die "$(basename $0) will only work if it can find a spec file in the current directory or a spec file was specified with --spec <specfile>.  An example spec file can be created with pkgit-create-skeleton-spec-file."
fi
verbose_echo "Using spec file = $spec"

# Check we are in a git repo
git status >/dev/null 2>&1
if [ $? != 0 ]; then
    die "Cannot run this script outside of a git repository"
fi

# Normally insist that all files are checked in, but if the user specifies "unclean" then skip the checks
if [ -z "$unclean" ]; then
    # Refuse to package if there are untracked files (if .gitignore knows about them then it is OK to proceed)
    if [ $(git clean -d -n | wc -l) != 0 ]; then
        echo >&2 "Refusing to publish: the following files are currently untracked by git: "
        git clean -d -n |sed 's/Would remove /\t/g'
        die "Please commit them, stash them, add them to a .gitignore or remove them."
    fi

    # Disallow unstaged changes in the working tree
    git diff --name-status --ignore-submodules --exit-code 2>&1 >/dev/null
    if [ $? != 0 ] ; then
        echo >&2 "Refusing to publish: you have unstaged changes."
        git diff --name-status --ignore-submodules >&2
        die "Please commit them, stash them or remove them."
    fi

    # Disallow uncommitted changes in the staging area
    git diff --staged --quiet --ignore-submodules --exit-code 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo >&2 "Refusing to publish: your staging area contains uncommitted changes."
        git diff --staged --name-status --ignore-submodules >&2
        die "Please commit them or remove them from the staging area."
    fi
fi

# If only doing a sandbox build then we don't need to check that all has been pushed to the central repo
if [ -z "$sandbox" ]; then
    # Refuse to package if the local git repo is ahead of the central repo
    # Note that the other way around is OK.  That is, the central repo may be in advance of the local repo.
    # Make the assumption that if branch is not master (so on a detached HEAD or some other branch) then the user actually knows what they are doing
    if [ "$current_branch" = "master" ]; then
        count_ahead=$(git log origin/master..HEAD --format=oneline |wc -l)
        if [ $count_ahead -gt 0 ]; then
            die "Refusing to publish: Your branch is ahead of 'origin/master' by $count_ahead commit(s). Please push these commits to the central repo before attempting to package." 
        fi
    fi
fi

# Time to tag the repo.
if [ -z "$sandbox" ]; then
    tag_cmd="$(dirname $0)/pkgit-tag-next $debug --message=\"$message\" $pretend $verbose ${spec%.spec} |tail -1"
    verbose_echo "Calling $tag_cmd"
    tag_name=$(eval "$tag_cmd")
    if [ $? != 0 ]; then
        die "Tagging unsuccessful.  Can't proceed. :("
    fi
else
    tag_name=${spec%.spec}-0.0.0-0
    verbose_echo "Sandbox version being created.  Assigned version = $tag_name"
fi    

# Extract the version, release from the tag_name
release=${tag_name##*-}                # Release is everything after the last minus sign.  Mostly this will be 1
version=${tag_name#${spec%.spec}-*}    # Remove the spec (package) name from the start; leaving something like 3.0.8-1
version=${version%-*}                  # Remove the release number from the end; leaving something like 3.0.8

# Release should be a number
TESTVAR="$(echo "$release" | sed 's/[0-9]*//g' )"
[ "${TESTVAR}"x = ""x ] || die "Illegal release number: $release"

# Version should be number.number.number
TESTVAR="$(echo "$version" | sed 's/[0-9]*//g' )"
[ "${TESTVAR}"x = ".."x ] || die "Illegal version number: $version"

verbose_echo "Tag name:           $tag_name"
verbose_echo "Spec file:          $spec"
verbose_echo "Version:            $version"
verbose_echo "Release:            $release"
verbose_echo ""

# Normally insist that all files are checked in, but if the user specifies "unclean" then skip the checks
if [ -z "$unclean" ]; then
    if [ -n "$pretend" ]; then
        die "Pretend mode can go no further.  Aborting."
    fi

    count=$(git clean -x -n -d |wc -l)
    if [ $count -gt 0 ]; then
        echo ^^^^^^ WARNING ^^^^^^
        echo If you proceed you
        git clean -x -n -d
        echo
        echo "Proceed (y/N)"
        read user_choice
        if [ $user_choice = "Y" ] || [ $user_choice = "y" ]; then
            echo "Cleaning out any uncommitted files..."
            git reset --hard
            git clean -x  -f -d
        else
            exit 1
        fi
    fi
fi

# Figure out some information about the repository and project spec file for later use
current_specfile_path=$(pwd)


#
# Now make the package
#

# At this point in time we will only support the source gzipped tarball with the .tgz extension
grep Source: $spec |grep tgz >/dev/null
if [ $? = 1 ]; then
    die "At this point in time we will only support the source gzipped tarball with the .tgz extension"
fi

rpmhome=$(rpm --eval %_topdir)

# Do not build in the root dir of the filesystem 
if [ $rpmhome = "/" ]; then
    die "Refusing to build with when the top level build directory is /"
fi

verbose_echo "Building in $rpmhome"
mkdir -p $rpmhome  || die "Could not make the $rpmhome directory"
cd $rpmhome  >/dev/null 
rpmdev-setuptree  || die "Failed to create the expected rpmbuild expected directory structure"

pkgit-create-tarball $debug $verbose --project-dir="$current_specfile_path" --tag-name="$tag_name" || die "Failed creating tarball"

# build RPM
verbose_echo "Building RPM with rpmbuild"
cd $rpmhome/SPECS  >/dev/null
if [ -z $verbose ]; then
    QUIET_FLAG=--quiet
fi

rpmbuild --clean $QUIET_FLAG -ba $(basename $spec) || die "Failed in rpmbuild"
cd $rpmhome >/dev/null

# move the newly built rpms to the project directory
find -name "${spec%.spec}*$version-$release*.rpm" -exec mv {} $current_specfile_path \;  >/dev/null

cd $current_specfile_path  >/dev/null







