#!/usr/bin/env sh

# Write a skeleton spec file 

usage()
{
    echo "Usage: $(basename $0)"
    echo "Write out a very simple and incomplete spec file"
    echo "This is just to get you started"
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]; then
    usage
    exit
fi

if [ "$1" = "--version" ]; then
    echo PKGIT_PROJECT_VERSION
    exit
fi



project_name=$(basename $PWD)
spec_filename=${project_name}.spec

if [ -e $spec_filename ]; then
    echo $spec_filename already exists
    exit 0
fi

cat >$spec_filename  <<EOF
Summary: $project_name - A very simple package
Name: $project_name
Version: %{version_base}
Release: %{version_release}%{?org_tag}%{?dist}
Source: %{name}-%{version}.tgz
License: Proprietary, Redistribution not allowed
Group: Applications/Other
Buildroot: %_tmppath/%{name}-%{version}

%description
$project_name - What does this project actually do?


%prep
%setup

%build
test %{buildroot} != "/" && rm -rf %{buildroot}

%install
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_mandir}/man1/

install \$(find -L . -type f -executable  2>/dev/null | perl -n -e 'print unless m!(/test/|/bin/|/\.git/|.gitignore|.*\.rpm$/)!') %{buildroot}%{_bindir}

%clean
test "%{buildroot}" != "/" && rm -rf %{buildroot}

%files
%defattr(-,root,root)
%attr(0755,-,-)%{_bindir}/*
EOF
