#!/bin/dash

# pkgit-tag-next 
# Insert a tag into the git repo at HEAD which has the next possible version number for the current project
# For example, if you are in a directory which contains a spec file called myproject.spec
# then look at all tags in the current git repo and search for all version numbers.
# Determine the greatest version number, e.g., 1.0.5-4.  Then insert a tag 

usage()
{
    echo "$(basename $0)  TODO: write help"
}


if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]; then
    usage
fi    

if [ "$1" = "--version" ]; then
    echo 0.0.0-1
fi


